# BackendTLSPolicy instrui o NGINX Gateway Fabric a abrir uma conexão
# TLS com o openbao-restapi, verificando o cert com o CA interno do cluster.
# Precisa estar no mesmo namespace do Service que está sendo protegido.
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: openbao-server
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: openbao-restapi
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: cluster-internal-ca
    hostname: openbao-restapi.openbao.svc.cluster.local
