apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-gateway-fabric
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - gateway-api
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /metrics
