apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
spec:
  destination:
    namespace: gateway-api
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://charts.nginx.com/stable
    chart: nginx-gateway
    targetRevision: 2.4.*
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# Antes de instalar o Helm Chart, aplique os CRDs:
# kubectl kustomize https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard | kubectl apply -f -