apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Projeto para gerenciar serviços de infraestrutura
  destinationServiceAccounts:
  - defaultServiceAccount: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - git@github.com:nmvinicius/k-stack.git
  - '*'
