apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.20.*
      helm:
        values: |-
          crds:
            enabled: true
          config:
            enableGatewayAPI: true
          prometheus:
            enabled: true
            servicemonitor:
              enabled: true
              labels:
                release: prometheus
          
    - repoURL: git@github.com:nmvinicius/k-stack.git
      targetRevision: HEAD
      path: infrastructure/cert-manager/configs
      directory:
        recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
