apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    namespace: gateway-api
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/nginx/nginx-gateway-fabric
      targetRevision: v2.4.2
      path: config/crd/gateway-api/experimental
    - chart: nginx-gateway-fabric
      repoURL: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
      targetRevision: 2.4.2
      helm:
        releaseName: nginx-gateway-fabric
        valuesObject:
          certGenerator:
            enable: false
          nginxGateway:
            gwAPIExperimentalFeatures:
              enable: true
    - repoURL: git@github.com:nmvinicius/k-stack.git
      targetRevision: HEAD
      path: infrastructure/gateway/configs
      directory:
        recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      name: nginx-gateway-fabric-cert-generator
      jsonPointers: ["/metadata/annotations"]
    - group: rbac.authorization.k8s.io
      kind: Role
      name: nginx-gateway-fabric-cert-generator
      jsonPointers: ["/metadata/annotations"]
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: nginx-gateway-fabric-cert-generator
      jsonPointers: ["/metadata/annotations"]
    - group: batch
      kind: Job
      name: nginx-gateway-fabric-cert-generator
      jsonPointers: ["/metadata/annotations"]
