apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    namespace: stackgres
    server: https://kubernetes.default.svc
  sources:
    - chart: stackgres-operator
      repoURL: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
      targetRevision: 1.18.*
      helm:
        releaseName: stackgres-operator
        valuesObject:
          stackgres-operator:
            resources:
              limits:
                cpu: "500m"
                memory: "1Gi"
              requests:
                cpu: "200m"
                memory: "512Mi"
          prometheus:
            enabled: true
            operator: true
            grafana:
              enabled: true
          adminui:
            service:
              type: ClusterIP
          cert:
            createForWebApi: true
            webSecretName: stackgres-web-tls
            regenerateWebCert: true
            regenerateWebRsa: true
    - repoURL: git@github.com:nmvinicius/k-stack.git
      targetRevision: HEAD
      path: infrastructure/stackgres/configs
      directory:
        recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Limit=1
      - CreateNamespace=true
      - ServerSideApply=true
